insert into tb_categoria (nome, criada_Em) values ('Informática', NOW());
insert into tb_categoria (nome, criada_Em) values ('Eletrônicos', NOW());
insert into tb_categoria (nome, criada_Em) values ('Eletrodomésticos', NOW());
insert into tb_categoria (nome, criada_Em) values ('Telefonia', NOW());
insert into tb_categoria (nome, criada_Em) values ('Games', NOW());
insert into tb_categoria (nome, criada_Em) values ('Livros', NOW());
insert into tb_categoria (nome, criada_Em) values ('Papelaria', NOW());
insert into tb_categoria (nome, criada_Em) values ('Móveis', NOW());
insert into tb_categoria (nome, criada_Em) values ('Casa e Decoração', NOW());
insert into tb_categoria (nome, criada_Em) values ('Moda Masculina', NOW());
insert into tb_categoria (nome, criada_Em) values ('Moda Feminina', NOW());
insert into tb_categoria (nome, criada_Em) values ('Esportes e Lazer', NOW());
insert into tb_categoria (nome, criada_Em) values ('Ferramentas', NOW());
insert into tb_categoria (nome, criada_Em) values ('Pet Shop', NOW());
insert into tb_categoria (nome, criada_Em) values ('Automotivo', NOW());
insert into tb_categoria (nome, criada_Em) values ('Beleza e Saúde', NOW());
insert into tb_categoria (nome, criada_Em) values ('Brinquedos', NOW());
insert into tb_categoria (nome, criada_Em) values ('Instrumentos Musicais', NOW());
insert into tb_categoria (nome, criada_Em) values ('Jardinagem', NOW());
insert into tb_categoria (nome, criada_Em) values ('Supermercado', NOW());
insert into tb_categoria (nome, criada_Em) values ('Bebidas', NOW());
insert into tb_categoria (nome, criada_Em) values ('Cama, Mesa e Banho', NOW());
insert into tb_categoria (nome, criada_Em) values ('Construção Civil', NOW());
insert into tb_categoria (nome, criada_Em) values ('Segurança e Monitoramento', NOW());
insert into tb_categoria (nome, criada_Em) values ('Energia Solar', NOW());