insert into tb_categoria (nome) values ('Informática');
insert into tb_categoria (nome) values ('Eletrônicos');
insert into tb_categoria (nome) values ('Eletrodomésticos');
insert into tb_categoria (nome) values ('Telefonia');
insert into tb_categoria (nome) values ('Games');
insert into tb_categoria (nome) values ('Livros');
insert into tb_categoria (nome) values ('Papelaria');
insert into tb_categoria (nome) values ('Móveis');
insert into tb_categoria (nome) values ('Casa e Decoração');
insert into tb_categoria (nome) values ('Moda Masculina');
insert into tb_categoria (nome) values ('Moda Feminina');
insert into tb_categoria (nome) values ('Esportes e Lazer');
insert into tb_categoria (nome) values ('Ferramentas');
insert into tb_categoria (nome) values ('Pet Shop');
insert into tb_categoria (nome) values ('Automotivo');
insert into tb_categoria (nome) values ('Beleza e Saúde');
insert into tb_categoria (nome) values ('Brinquedos');
insert into tb_categoria (nome) values ('Instrumentos Musicais');
insert into tb_categoria (nome) values ('Jardinagem');
insert into tb_categoria (nome) values ('Supermercado');
insert into tb_categoria (nome) values ('Bebidas');
insert into tb_categoria (nome) values ('Cama, Mesa e Banho');
insert into tb_categoria (nome) values ('Construção Civil');
insert into tb_categoria (nome) values ('Segurança e Monitoramento');
insert into tb_categoria (nome) values ('Energia Solar');