insert into tb_categoria (id, nome) values (1,  'Informática');
insert into tb_categoria (id, nome) values (2,  'Eletrônicos');
insert into tb_categoria (id, nome) values (3,  'Eletrodomésticos');
insert into tb_categoria (id, nome) values (4,  'Telefonia');
insert into tb_categoria (id, nome) values (5,  'Games');
insert into tb_categoria (id, nome) values (6,  'Livros');
insert into tb_categoria (id, nome) values (7,  'Papelaria');
insert into tb_categoria (id, nome) values (8,  'Móveis');
insert into tb_categoria (id, nome) values (9,  'Casa e Decoração');
insert into tb_categoria (id, nome) values (10, 'Moda Masculina');
insert into tb_categoria (id, nome) values (11, 'Moda Feminina');
insert into tb_categoria (id, nome) values (12, 'Esportes e Lazer');
insert into tb_categoria (id, nome) values (13, 'Ferramentas');
insert into tb_categoria (id, nome) values (14, 'Pet Shop');
insert into tb_categoria (id, nome) values (15, 'Automotivo');
insert into tb_categoria (id, nome) values (16, 'Beleza e Saúde');
insert into tb_categoria (id, nome) values (17, 'Brinquedos');
insert into tb_categoria (id, nome) values (18, 'Instrumentos Musicais');
insert into tb_categoria (id, nome) values (19, 'Jardinagem');
insert into tb_categoria (id, nome) values (20, 'Supermercado');
insert into tb_categoria (id, nome) values (21, 'Bebidas');
insert into tb_categoria (id, nome) values (22, 'Cama, Mesa e Banho');
insert into tb_categoria (id, nome) values (23, 'Construção Civil');
insert into tb_categoria (id, nome) values (24, 'Segurança e Monitoramento');
insert into tb_categoria (id, nome) values (25, 'Energia Solar');